// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8J-x9LZSiN-LesKThZmaD2sjRlanyVhs',
    appId: '1:298811452830:web:aa722a46cf3bb86bca7a8f',
    messagingSenderId: '298811452830',
    projectId: 'donemprojem-45aed',
    authDomain: 'donemprojem-45aed.firebaseapp.com',
    storageBucket: 'donemprojem-45aed.firebasestorage.app',
    measurementId: 'G-FSVW0RMTX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHsbYOBT_neKsPSQFeTXhdtoJCZ11XnUk',
    appId: '1:298811452830:android:e7ebf8372128d99aca7a8f',
    messagingSenderId: '298811452830',
    projectId: 'donemprojem-45aed',
    storageBucket: 'donemprojem-45aed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvIZuE2bt3C6vOXV0byBfDgeJncPQkhfA',
    appId: '1:298811452830:ios:3b8d7080ad96ee07ca7a8f',
    messagingSenderId: '298811452830',
    projectId: 'donemprojem-45aed',
    storageBucket: 'donemprojem-45aed.firebasestorage.app',
    iosBundleId: 'com.example.donemProjem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvIZuE2bt3C6vOXV0byBfDgeJncPQkhfA',
    appId: '1:298811452830:ios:3b8d7080ad96ee07ca7a8f',
    messagingSenderId: '298811452830',
    projectId: 'donemprojem-45aed',
    storageBucket: 'donemprojem-45aed.firebasestorage.app',
    iosBundleId: 'com.example.donemProjem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8J-x9LZSiN-LesKThZmaD2sjRlanyVhs',
    appId: '1:298811452830:web:58321b4788a40d26ca7a8f',
    messagingSenderId: '298811452830',
    projectId: 'donemprojem-45aed',
    authDomain: 'donemprojem-45aed.firebaseapp.com',
    storageBucket: 'donemprojem-45aed.firebasestorage.app',
    measurementId: 'G-32CLBNYC9W',
  );

}